spring.application.name=The_Last_Stand_Backend

# SQLite file location
spring.datasource.url=jdbc:sqlite:LastStand.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate Settings (IMPORTANT!)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
